### ISSUE TITLE
nxyoutube.js loads before jquery

### ISSUE THREAD

**Issue by mojeweb** [marcorensch/nx-youtube-Custom-Field#5]
As nxyoutube loads before jquery, plugin not working. 
Joomla 3.9.1
Template Protostar and masterbootstrap.

Error in console Uncaught ReferenceError: jQuery is not defined at nxyoutube.js:29

**Comment by marcorensch** [comment]
Thx for your feedback i will have a look tomorrow.

**Comment by marcorensch** [comment]
Reproduced in version 1.3
solved in version 1.3.1
